version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  webapp:
    image: your-aspnet-app:latest  # Замените на имя вашего образа
    container_name: aspnet_core_app
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=myappdb;Username=postgres;Password=your_secure_password
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge